package view;

import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import static java.lang.System.err;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;     //JOptionPane, is so that we can display error messages.
import javax.swing.JPanel;
/**
 * @author Me
 */
public class Workers extends javax.swing.JFrame {
    Connection con;     //connection object
    Statement stmt;     //statement object
    ResultSet rs;       //ResultSet object
    int curRow = 0;
    
    /*private ImageIcon image1;
    private JLabel label1;
    
    private void Workers(){
        setLayout(new FlowLayout());
        image1 = new ImageIcon(getClass().getResource("/images/bbclogo.png"));
        label1 = new JLable(image1);
        URL url = this.getClass().getResource("/images/bbclogo.png");
        try {
            BufferedImage img = ImageIO.read(url);
        } catch (IOException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }
        add(img);
        
    }*/
    /*JPanel jp = new JPanel();
    JLabel jl = new JLabel();
    
    public Workers(){
        setTitle("Tutorial");
        setVisible(true);
        setSize(400,200);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        jl.setIcon(new ImageIcon("C:\\Users\\Me\\Desktop\\bbclogo.png"));
        jp.add(jl);
        add(jp);
        
        validate();
        
    }*/
    /**
     * Creates new form Workers
     */
    public Workers() {
        initComponents();
        DoConnect();
    }
    public void DoConnect( ) {
        try {
            String host = "jdbc:derby://localhost:1527/App";
            String username = "App";
            String password = "app";
            con = DriverManager.getConnection(host, username, password);
            //Here, we're creating a Statement object called stmt. The Statement object needs a Connection object, with
            //the createStatment method.
            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );  //ResultSet.TYPE_SCROLL_SENSITIVE
            String SQL = "SELECT * FROM CUSTOMER";
            rs = stmt.executeQuery( SQL );
            //while (rs.next( )) {  //This will move the Cursor to the first record in the table.
                //int id_col = rs.getInt("ID");
                rs.next();
                String cus_name = rs.getString("NAME");
                String cus_address = rs.getString("ADDRESS");
                String cus_usertype = rs.getString("USERTYPE");
                int cus_noofappsused_col = rs.getInt("NOOFAPPSUSED");
                String cus_noofappsused = Integer.toString(cus_noofappsused_col);
                //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
                textName.setText(cus_name);
                textAddress.setText(cus_address);
                textUserType.setText(cus_usertype);
                textNoOfAppsUsed.setText(cus_noofappsused);
            //}
        }
        catch ( SQLException err ) {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textAddress = new javax.swing.JTextField();
        textUserType = new javax.swing.JTextField();
        textNoOfAppsUsed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnUpdateRecord = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        btnSaveRecord = new javax.swing.JButton();
        btnCancelNewRecord = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });

        textUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("No of Apps Used");

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnUpdateRecord.setText("Update Record");
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        btnNewRecord.setText("New Record");
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setText("Delete Record");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        btnSaveRecord.setText("Save New Record");
        btnSaveRecord.setEnabled(false);
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });

        btnCancelNewRecord.setText("Cancel New Record");
        btnCancelNewRecord.setEnabled(false);
        btnCancelNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewRecordActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textUserType)
                    .addComponent(textAddress)
                    .addComponent(textNoOfAppsUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdateRecord)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewRecord)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteRecord)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFirst)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast)
                        .addGap(43, 43, 43))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnSaveRecord)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelNewRecord))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNoOfAppsUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateRecord)
                    .addComponent(btnNewRecord)
                    .addComponent(btnDeleteRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveRecord)
                    .addComponent(btnCancelNewRecord))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void btnCancelNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewRecordActionPerformed
        try {
            // TODO add your handling code here:
            rs.absolute( curRow );
            /*To move the Cursor back to the row it was previously pointing to, we can use the absolute method:
            The absolute method moves the Cursor to a fixed position in the ResultSet. We want to move it the
            value that we stored in the variable curRow.*/
            textName.setText( rs.getString("NAME") );
            textAddress.setText( rs.getString("ADDRESS") );
            textUserType.setText( rs.getString("USERTYPE") );
            textNoOfAppsUsed.setText( Integer.toString( rs.getInt("NOOFAPPSUSED" )) );

            btnFirst.setEnabled( true );
            btnPrevious.setEnabled( true ) ;
            btnNext.setEnabled( true );
            btnLast.setEnabled( true );
            btnUpdateRecord.setEnabled( true );
            btnDeleteRecord.setEnabled( true );
            btnNewRecord.setEnabled( true );

            btnSaveRecord.setEnabled( false );
            btnCancelNewRecord.setEnabled( false );
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnCancelNewRecordActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed
        // TODO add your handling code here:
        String cus_name = textName.getText();
        String cus_address = textAddress.getText();
        String cus_usertype = textUserType.getText();
        String cus_noofappsused_col = textNoOfAppsUsed.getText();

        int newNoOfAppsUsed = Integer.parseInt(cus_noofappsused_col);

        try {
            rs.moveToInsertRow( );

            rs.updateString( "NAME", cus_name );
            rs.updateString( "ADDRESS", cus_address );
            rs.updateString( "USERTYPE", cus_usertype );
            rs.updateInt( "NOOFAPPSUSED", newNoOfAppsUsed );

            rs.insertRow( );

            stmt.close();
            rs.close();

            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );  //ResultSet.TYPE_SCROLL_SENSITIVE
            String SQL = "SELECT * FROM CUSTOMER";
            rs = stmt.executeQuery( SQL );

            rs.next();
            String cus_name2 = rs.getString("NAME");
            String cus_address2 = rs.getString("ADDRESS");
            String cus_usertype2 = rs.getString("USERTYPE");
            int cus_noofappsused_col2 = rs.getInt("NOOFAPPSUSED");
            String cus_noofappsused = Integer.toString(cus_noofappsused_col2);
            //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
            textName.setText(cus_name2);
            textAddress.setText(cus_address2);
            textUserType.setText(cus_usertype2);
            textNoOfAppsUsed.setText(cus_noofappsused);

            btnFirst.setEnabled( true );
            btnPrevious.setEnabled( true ) ;
            btnNext.setEnabled( true );
            btnLast.setEnabled( true );
            btnUpdateRecord.setEnabled( true );
            btnDeleteRecord.setEnabled( true );
            btnNewRecord.setEnabled( true );

            btnSaveRecord.setEnabled( false );
            btnCancelNewRecord.setEnabled( false );
            //}
        }
        catch ( SQLException err ) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnSaveRecordActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:
        try {
            rs.deleteRow( );
            stmt.close();
            rs.close();

            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );  //ResultSet.TYPE_SCROLL_SENSITIVE
            String SQL = "SELECT * FROM CUSTOMER";
            rs = stmt.executeQuery( SQL );

            rs.next();
            String cus_name = rs.getString("NAME");
            String cus_address = rs.getString("ADDRESS");
            String cus_usertype = rs.getString("USERTYPE");
            int cus_noofappsused_col = rs.getInt("NOOFAPPSUSED");
            String cus_noofappsused = Integer.toString(cus_noofappsused_col);
            //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
            textName.setText(cus_name);
            textAddress.setText(cus_address);
            textUserType.setText(cus_usertype);
            textNoOfAppsUsed.setText(cus_noofappsused);
        }
        catch ( SQLException err ) {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
        try {
            // TODO add your handling code here:
            curRow = rs.getRow();

            textName.setText("");
            textAddress.setText("");
            textUserType.setText("");
            textNoOfAppsUsed.setText("");

            btnFirst.setEnabled( false );
            btnPrevious.setEnabled( false ) ;
            btnNext.setEnabled( false );
            btnLast.setEnabled( false );
            btnUpdateRecord.setEnabled( false );
            btnDeleteRecord.setEnabled( false );
            btnNewRecord.setEnabled( false );

            btnSaveRecord.setEnabled( true );
            btnCancelNewRecord.setEnabled( true );
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        // TODO add your handling code here:
        String cus_name = textName.getText();
        String cus_address = textAddress.getText();
        String cus_usertype = textUserType.getText();
        String cus_noofappsused_col = textNoOfAppsUsed.getText();

        int newNoOfAppsUsed = Integer.parseInt(cus_noofappsused_col);

        try {
            rs.updateString( "NAME", cus_name );
            rs.updateString( "ADDRESS", cus_address );
            rs.updateString( "USERTYPE", cus_usertype );
            rs.updateInt( "NOOFAPPSUSED", newNoOfAppsUsed );
            rs.updateRow( );
            JOptionPane.showMessageDialog(Workers.this, "Updated");
        } catch (SQLException err) {
            //System.out.println(err.getMessage());
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        try {
            rs.last();
            String cus_name = rs.getString("NAME");
            String cus_address = rs.getString("ADDRESS");
            String cus_usertype = rs.getString("USERTYPE");
            int cus_noofappsused_col = rs.getInt("NOOFAPPSUSED");
            String cus_noofappsused = Integer.toString(cus_noofappsused_col);
            //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
            textName.setText(cus_name);
            textAddress.setText(cus_address);
            textUserType.setText(cus_usertype);
            textNoOfAppsUsed.setText(cus_noofappsused);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.next()) {
                String cus_name = rs.getString("NAME");
                String cus_address = rs.getString("ADDRESS");
                String cus_usertype = rs.getString("USERTYPE");
                int cus_noofappsused_col = rs.getInt("NOOFAPPSUSED");
                String cus_noofappsused = Integer.toString(cus_noofappsused_col);
                //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
                textName.setText(cus_name);
                textAddress.setText(cus_address);
                textUserType.setText(cus_usertype);
                textNoOfAppsUsed.setText(cus_noofappsused);
            }
            else {
                rs.previous( );
                JOptionPane.showMessageDialog(Workers.this, "End of File");
            }
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        try {
            if (rs.previous()) {
                String cus_name = rs.getString("NAME");
                String cus_address = rs.getString("ADDRESS");
                String cus_usertype = rs.getString("USERTYPE");
                int cus_noofappsused_col = rs.getInt("NOOFAPPSUSED");
                String cus_noofappsused = Integer.toString(cus_noofappsused_col);
                //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
                textName.setText(cus_name);
                textAddress.setText(cus_address);
                textUserType.setText(cus_usertype);
                textNoOfAppsUsed.setText(cus_noofappsused);
            }
            else {
                rs.next();
                JOptionPane.showMessageDialog(Workers.this, "End of File");
            }
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        try {
            rs.first();
            String cus_name = rs.getString("NAME");
            String cus_address = rs.getString("ADDRESS");
            String cus_usertype = rs.getString("USERTYPE");
            int cus_noofappsused_col = rs.getInt("NOOFAPPSUSED");
            String cus_noofappsused = Integer.toString(cus_noofappsused_col);
            //System.out.println( cus_name + " " + cus_address + " " + cus_usertype + " " + cus_noofappsused );
            textName.setText(cus_name);
            textAddress.setText(cus_address);
            textUserType.setText(cus_usertype);
            textNoOfAppsUsed.setText(cus_noofappsused);
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(Workers.this, err.getMessage());
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void textUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserTypeActionPerformed

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workers().setVisible(true);
            }
        });*/
        Workers gui = new Workers();
        gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        gui.setVisible(true);
        gui.pack();
        gui.setTitle("Image Program");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelNewRecord;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNoOfAppsUsed;
    private javax.swing.JTextField textUserType;
    // End of variables declaration//GEN-END:variables

    private static class ImageTutorial {

        public ImageTutorial() {
        }

        private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class JLable extends JLabel {

        public JLable(ImageIcon image1) {
        }
    }

}
